---
- name: This play installs nmap
  hosts: ansible214-c-vm1
  vars:
    packages: nmap
  tasks:
    - name: Task1 installs package {{ packages }}
      yum:
        name: "{{ packages }}"
        state: latest
      when: packages is defined
