---

- name: This play insatlls packages using loops
  hosts: ansible214-c-vm2
  tasks:
    - name: Task1
      yum:
        name: "{{ packages }}"
        state: present
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 2147483648
